version: '3.7'

services:

      publishen-product:
        build: ./publish
        ports:
          - 8383:50050
        volumes:
          - .:/var/www/publishen/publish
          - .:/publishen
          - $GOPATH/pkg/mod:/go/pkg/mod
        environment:
          GOPATH: /go
          MICRO_REGISTRY: "mdns"
          MICRO_ADDRESS:  ":50050"
          DB_HOST:  "arangoDB:8529"



      arangoDB:
        image: arangodb/arangodb:latest
        ports:
          - 8529:8529
        env_file:
          - docker.env