// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package publishen_product_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProductShareState int32

const (
	Product_PUBLIC  ProductShareState = 0
	Product_PRIVATE ProductShareState = 1
)

var ProductShareState_name = map[int32]string{
	0: "PUBLIC",
	1: "PRIVATE",
}
var ProductShareState_value = map[string]int32{
	"PUBLIC":  0,
	"PRIVATE": 1,
}

func (x ProductShareState) String() string {
	return proto.EnumName(ProductShareState_name, int32(x))
}
func (ProductShareState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_product_e19183da4dd63440, []int{0, 0}
}

type ProductClass int32

const (
	Product_I_WANT ProductClass = 0
	Product_I_HAVE ProductClass = 1
)

var ProductClass_name = map[int32]string{
	0: "I_WANT",
	1: "I_HAVE",
}
var ProductClass_value = map[string]int32{
	"I_WANT": 0,
	"I_HAVE": 1,
}

func (x ProductClass) String() string {
	return proto.EnumName(ProductClass_name, int32(x))
}
func (ProductClass) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_product_e19183da4dd63440, []int{0, 1}
}

type ProductGroup int32

const (
	Product_ARTICLE ProductGroup = 0
	Product_PRODUCT ProductGroup = 1
	Product_GALLERY ProductGroup = 2
	Product_VIDEO   ProductGroup = 3
)

var ProductGroup_name = map[int32]string{
	0: "ARTICLE",
	1: "PRODUCT",
	2: "GALLERY",
	3: "VIDEO",
}
var ProductGroup_value = map[string]int32{
	"ARTICLE": 0,
	"PRODUCT": 1,
	"GALLERY": 2,
	"VIDEO":   3,
}

func (x ProductGroup) String() string {
	return proto.EnumName(ProductGroup_name, int32(x))
}
func (ProductGroup) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_product_e19183da4dd63440, []int{0, 2}
}

type Product struct {
	Title                string       `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Banner               string       `protobuf:"bytes,3,opt,name=banner,proto3" json:"banner,omitempty"`
	Images               []string     `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Location             *Location    `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Attributes           []*Attribute `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty"`
	ShareGroupID         string       `protobuf:"bytes,9,opt,name=shareGroupID,proto3" json:"shareGroupID,omitempty"`
	UserID               string       `protobuf:"bytes,10,opt,name=userID,proto3" json:"userID,omitempty"`
	Tags                 []string     `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_e19183da4dd63440, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetBanner() string {
	if m != nil {
		return m.Banner
	}
	return ""
}

func (m *Product) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Product) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Product) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Product) GetShareGroupID() string {
	if m != nil {
		return m.ShareGroupID
	}
	return ""
}

func (m *Product) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Product) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Location struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_e19183da4dd63440, []int{1}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Attribute struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_e19183da4dd63440, []int{2}
}
func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (dst *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(dst, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Attribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Response struct {
	ErrorMessage         string     `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Success              bool       `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	DocumentID           string     `protobuf:"bytes,3,opt,name=documentID,proto3" json:"documentID,omitempty"`
	Product              *Product   `protobuf:"bytes,4,opt,name=product,proto3" json:"product,omitempty"`
	Products             []*Product `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_e19183da4dd63440, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetDocumentID() string {
	if m != nil {
		return m.DocumentID
	}
	return ""
}

func (m *Response) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Response) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "publishen.product.service.Product")
	proto.RegisterType((*Location)(nil), "publishen.product.service.Location")
	proto.RegisterType((*Attribute)(nil), "publishen.product.service.Attribute")
	proto.RegisterType((*Response)(nil), "publishen.product.service.Response")
	proto.RegisterEnum("publishen.product.service.ProductShareState", ProductShareState_name, ProductShareState_value)
	proto.RegisterEnum("publishen.product.service.ProductClass", ProductClass_name, ProductClass_value)
	proto.RegisterEnum("publishen.product.service.ProductGroup", ProductGroup_name, ProductGroup_value)
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_product_e19183da4dd63440) }

var fileDescriptor_product_e19183da4dd63440 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0x6e, 0x9a, 0x6b, 0x9b, 0x4e, 0x3c, 0x09, 0x83, 0x48, 0x3c, 0x44, 0x4b, 0x14, 0xe9, 0x53,
	0x1f, 0x7a, 0x4f, 0x82, 0x28, 0xb1, 0x29, 0x67, 0xa0, 0x7a, 0x25, 0xf6, 0x2a, 0xfa, 0x72, 0x6c,
	0xd3, 0xa1, 0x17, 0xcc, 0x25, 0x61, 0x77, 0x73, 0xe0, 0x7f, 0xf4, 0x77, 0xf8, 0x3b, 0x64, 0x77,
	0x93, 0xda, 0x7b, 0xb0, 0xdc, 0xdb, 0x7c, 0xdf, 0xcc, 0x37, 0xc9, 0xcc, 0x7c, 0x0b, 0xa7, 0x15,
	0x2f, 0xb7, 0x75, 0x2a, 0x27, 0x15, 0x2f, 0x65, 0x89, 0xcf, 0xaa, 0x7a, 0x93, 0x67, 0xe2, 0x86,
	0x8a, 0x49, 0x9b, 0x10, 0xc4, 0xef, 0xb2, 0x94, 0x82, 0xdf, 0x36, 0x0c, 0x96, 0x86, 0xc3, 0x27,
	0xd0, 0x93, 0x99, 0xcc, 0xc9, 0xb7, 0x46, 0xd6, 0x78, 0x98, 0x18, 0x80, 0x23, 0x70, 0xb7, 0x24,
	0x52, 0x9e, 0x55, 0x32, 0x2b, 0x0b, 0xbf, 0xab, 0x73, 0x87, 0x14, 0x3e, 0x85, 0xfe, 0x86, 0x15,
	0x05, 0x71, 0xdf, 0xd6, 0xc9, 0x06, 0x29, 0x3e, 0xbb, 0x65, 0x3b, 0x12, 0x7e, 0x6f, 0x64, 0x2b,
	0xde, 0x20, 0xfc, 0x00, 0x4e, 0x5e, 0xa6, 0x4c, 0xb7, 0xeb, 0x8f, 0xac, 0xb1, 0x3b, 0x7d, 0x35,
	0xf9, 0xef, 0x1f, 0x4e, 0x16, 0x4d, 0x69, 0xb2, 0x17, 0x61, 0x04, 0xc0, 0xa4, 0xe4, 0xd9, 0xa6,
	0x96, 0x24, 0xfc, 0xc1, 0xc8, 0x1e, 0xbb, 0xd3, 0xd7, 0x47, 0x5a, 0x84, 0x6d, 0x71, 0x72, 0xa0,
	0xc3, 0x00, 0x1e, 0x89, 0x1b, 0xc6, 0xe9, 0x82, 0x97, 0x75, 0x15, 0x47, 0xfe, 0x50, 0xff, 0xfc,
	0x3d, 0x4e, 0x8d, 0x50, 0x0b, 0xe2, 0x71, 0xe4, 0x83, 0x19, 0xcd, 0x20, 0x44, 0x38, 0x91, 0x6c,
	0x27, 0x7c, 0x57, 0x0f, 0xa6, 0xe3, 0xe0, 0x0d, 0xb8, 0x5a, 0x7b, 0x2d, 0x24, 0x93, 0x84, 0x00,
	0xfd, 0xe5, 0xd5, 0xc7, 0x45, 0x3c, 0xf3, 0x3a, 0xe8, 0xc2, 0x60, 0x99, 0xc4, 0xeb, 0x70, 0x35,
	0xf7, 0xac, 0xe0, 0x25, 0xf4, 0xd2, 0x9c, 0x09, 0xa1, 0x2a, 0xe2, 0xeb, 0x6f, 0xe1, 0x97, 0x95,
	0xd7, 0x31, 0xf1, 0xa7, 0x70, 0xad, 0x0a, 0xde, 0x42, 0x6f, 0xa7, 0xbe, 0xaf, 0x64, 0x61, 0xb2,
	0x8a, 0x67, 0x8b, 0x79, 0xdb, 0xe3, 0x32, 0xba, 0x9a, 0xad, 0x3c, 0x4b, 0x81, 0x8b, 0x70, 0xb1,
	0x98, 0x27, 0xdf, 0xbd, 0x2e, 0x0e, 0xa1, 0xb7, 0x8e, 0xa3, 0xf9, 0xa5, 0x67, 0x07, 0x11, 0x38,
	0xed, 0xbe, 0xf0, 0x0c, 0x9c, 0x9c, 0xc9, 0x4c, 0xd6, 0x5b, 0x73, 0xd1, 0x6e, 0xb2, 0xc7, 0xf8,
	0x1c, 0x86, 0x79, 0x59, 0xec, 0x4c, 0xb2, 0xab, 0x93, 0xff, 0x88, 0xe0, 0x1c, 0x86, 0xfb, 0x95,
	0xa1, 0x07, 0xf6, 0x4f, 0xfa, 0xd5, 0x78, 0x42, 0x85, 0xca, 0x27, 0x77, 0x2c, 0xaf, 0xa9, 0xf1,
	0x82, 0x01, 0xc1, 0x1f, 0x0b, 0x9c, 0x84, 0x44, 0x55, 0x16, 0x82, 0xd4, 0x6e, 0x89, 0xf3, 0x92,
	0x7f, 0x26, 0x21, 0xd8, 0xae, 0x75, 0xd4, 0x3d, 0x0e, 0x7d, 0x18, 0x88, 0x3a, 0x4d, 0x49, 0x08,
	0xdd, 0xc8, 0x49, 0x5a, 0x88, 0x2f, 0x00, 0xb6, 0x65, 0x5a, 0xdf, 0x52, 0x21, 0xe3, 0xa8, 0x31,
	0xd5, 0x01, 0x83, 0xef, 0x60, 0xd0, 0x9c, 0xd8, 0x3f, 0xd1, 0xfe, 0x09, 0x8e, 0x1c, 0xbf, 0x71,
	0x77, 0xd2, 0x4a, 0xf0, 0x3d, 0x38, 0x4d, 0x68, 0x8c, 0xf9, 0x30, 0xf9, 0x5e, 0x33, 0xcd, 0xe1,
	0x71, 0x13, 0x7f, 0x35, 0x35, 0xf8, 0x03, 0x4e, 0x67, 0x9c, 0x98, 0xa4, 0xf6, 0x25, 0x3d, 0xa0,
	0xe1, 0xd9, 0x31, 0xcf, 0xb7, 0x7b, 0x0c, 0x3a, 0x9b, 0xbe, 0x7e, 0xc2, 0xe7, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0x4b, 0x10, 0xb4, 0xd3, 0x03, 0x00, 0x00,
}
