// Code generated by protoc-gen-go. DO NOT EDIT.
// source: publish.proto

package publishen_publish_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublishShareState int32

const (
	Publish_PUBLIC  PublishShareState = 0
	Publish_PRIVATE PublishShareState = 1
)

var PublishShareState_name = map[int32]string{
	0: "PUBLIC",
	1: "PRIVATE",
}
var PublishShareState_value = map[string]int32{
	"PUBLIC":  0,
	"PRIVATE": 1,
}

func (x PublishShareState) String() string {
	return proto.EnumName(PublishShareState_name, int32(x))
}
func (PublishShareState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_publish_781860c19b2f2b5b, []int{1, 0}
}

type PublishClass int32

const (
	Publish_I_WANT PublishClass = 0
	Publish_I_HAVE PublishClass = 1
)

var PublishClass_name = map[int32]string{
	0: "I_WANT",
	1: "I_HAVE",
}
var PublishClass_value = map[string]int32{
	"I_WANT": 0,
	"I_HAVE": 1,
}

func (x PublishClass) String() string {
	return proto.EnumName(PublishClass_name, int32(x))
}
func (PublishClass) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_publish_781860c19b2f2b5b, []int{1, 1}
}

type PublishGroup int32

const (
	Publish_ARTICLE PublishGroup = 0
	Publish_PRODUCT PublishGroup = 1
	Publish_GALLERY PublishGroup = 2
	Publish_VIDEO   PublishGroup = 3
	Publish_JOB     PublishGroup = 4
	Publish_PROJECT PublishGroup = 5
)

var PublishGroup_name = map[int32]string{
	0: "ARTICLE",
	1: "PRODUCT",
	2: "GALLERY",
	3: "VIDEO",
	4: "JOB",
	5: "PROJECT",
}
var PublishGroup_value = map[string]int32{
	"ARTICLE": 0,
	"PRODUCT": 1,
	"GALLERY": 2,
	"VIDEO":   3,
	"JOB":     4,
	"PROJECT": 5,
}

func (x PublishGroup) String() string {
	return proto.EnumName(PublishGroup_name, int32(x))
}
func (PublishGroup) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_publish_781860c19b2f2b5b, []int{1, 2}
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_781860c19b2f2b5b, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Publish struct {
	ID                   string       `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Banner               string       `protobuf:"bytes,4,opt,name=banner,proto3" json:"banner,omitempty"`
	Images               []string     `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Location             *Location    `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Attributes           []*Attribute `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty"`
	ShareGroupID         string       `protobuf:"bytes,9,opt,name=shareGroupID,proto3" json:"shareGroupID,omitempty"`
	UserID               string       `protobuf:"bytes,10,opt,name=userID,proto3" json:"userID,omitempty"`
	Tags                 []string     `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	Key                  string       `protobuf:"bytes,12,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Publish) Reset()         { *m = Publish{} }
func (m *Publish) String() string { return proto.CompactTextString(m) }
func (*Publish) ProtoMessage()    {}
func (*Publish) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_781860c19b2f2b5b, []int{1}
}
func (m *Publish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Publish.Unmarshal(m, b)
}
func (m *Publish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Publish.Marshal(b, m, deterministic)
}
func (dst *Publish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Publish.Merge(dst, src)
}
func (m *Publish) XXX_Size() int {
	return xxx_messageInfo_Publish.Size(m)
}
func (m *Publish) XXX_DiscardUnknown() {
	xxx_messageInfo_Publish.DiscardUnknown(m)
}

var xxx_messageInfo_Publish proto.InternalMessageInfo

func (m *Publish) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Publish) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Publish) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Publish) GetBanner() string {
	if m != nil {
		return m.Banner
	}
	return ""
}

func (m *Publish) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Publish) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Publish) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Publish) GetShareGroupID() string {
	if m != nil {
		return m.ShareGroupID
	}
	return ""
}

func (m *Publish) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Publish) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Publish) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Location struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_781860c19b2f2b5b, []int{2}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Attribute struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_781860c19b2f2b5b, []int{3}
}
func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (dst *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(dst, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Attribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Response struct {
	ErrorMessage         string     `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Success              bool       `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	DocumentID           string     `protobuf:"bytes,3,opt,name=documentID,proto3" json:"documentID,omitempty"`
	Publish              *Publish   `protobuf:"bytes,4,opt,name=publish,proto3" json:"publish,omitempty"`
	Publishes            []*Publish `protobuf:"bytes,5,rep,name=publishes,proto3" json:"publishes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_781860c19b2f2b5b, []int{4}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetDocumentID() string {
	if m != nil {
		return m.DocumentID
	}
	return ""
}

func (m *Response) GetPublish() *Publish {
	if m != nil {
		return m.Publish
	}
	return nil
}

func (m *Response) GetPublishes() []*Publish {
	if m != nil {
		return m.Publishes
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "publishen.publish.service.Request")
	proto.RegisterType((*Publish)(nil), "publishen.publish.service.Publish")
	proto.RegisterType((*Location)(nil), "publishen.publish.service.Location")
	proto.RegisterType((*Attribute)(nil), "publishen.publish.service.Attribute")
	proto.RegisterType((*Response)(nil), "publishen.publish.service.Response")
	proto.RegisterEnum("publishen.publish.service.PublishShareState", PublishShareState_name, PublishShareState_value)
	proto.RegisterEnum("publishen.publish.service.PublishClass", PublishClass_name, PublishClass_value)
	proto.RegisterEnum("publishen.publish.service.PublishGroup", PublishGroup_name, PublishGroup_value)
}

func init() { proto.RegisterFile("publish.proto", fileDescriptor_publish_781860c19b2f2b5b) }

var fileDescriptor_publish_781860c19b2f2b5b = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x6d, 0xe2, 0x38, 0x8e, 0xc7, 0x4d, 0xb1, 0x56, 0x08, 0x99, 0x0a, 0x41, 0x64, 0x40, 0xea,
	0x29, 0x87, 0xf4, 0x8a, 0x04, 0x6e, 0x1c, 0x15, 0x17, 0x43, 0x22, 0x37, 0x6d, 0x45, 0x85, 0x84,
	0x36, 0xce, 0x90, 0x5a, 0xb8, 0xb6, 0xd9, 0x5d, 0x57, 0xea, 0x99, 0xcf, 0xe4, 0x07, 0xf8, 0x0c,
	0xb4, 0x6b, 0x3b, 0x6d, 0x0f, 0x44, 0xbd, 0xe4, 0xb6, 0xef, 0xcd, 0x9b, 0xa7, 0xd9, 0xf1, 0x5b,
	0x43, 0xbf, 0x28, 0x17, 0x69, 0xc2, 0xaf, 0x86, 0x05, 0xcb, 0x45, 0x4e, 0x9e, 0xd7, 0x10, 0xb3,
	0x61, 0x53, 0xe0, 0xc8, 0x6e, 0x92, 0x18, 0x5d, 0x13, 0x8c, 0x08, 0x7f, 0x95, 0xc8, 0x85, 0xfb,
	0xbb, 0x03, 0xc6, 0xac, 0x2a, 0x93, 0x3d, 0x68, 0x07, 0xbe, 0xd3, 0x1a, 0xb4, 0x0e, 0xcc, 0xa8,
	0x1d, 0xf8, 0xe4, 0x29, 0xe8, 0x22, 0x11, 0x29, 0x3a, 0x6d, 0x45, 0x55, 0x80, 0x0c, 0xc0, 0x5a,
	0x22, 0x8f, 0x59, 0x52, 0x88, 0x24, 0xcf, 0x1c, 0x4d, 0xd5, 0xee, 0x53, 0xe4, 0x19, 0x74, 0x17,
	0x34, 0xcb, 0x90, 0x39, 0x1d, 0x55, 0xac, 0x91, 0xe4, 0x93, 0x6b, 0xba, 0x42, 0xee, 0xe8, 0x03,
	0x4d, 0xf2, 0x15, 0x22, 0xef, 0xa1, 0x97, 0xe6, 0x31, 0x55, 0x76, 0xdd, 0x41, 0xeb, 0xc0, 0x1a,
	0xbd, 0x1e, 0xfe, 0x77, 0xf8, 0x61, 0x58, 0x4b, 0xa3, 0x75, 0x13, 0xf1, 0x01, 0xa8, 0x10, 0x2c,
	0x59, 0x94, 0x02, 0xb9, 0x63, 0x0c, 0xb4, 0x03, 0x6b, 0xf4, 0x66, 0x83, 0x85, 0xd7, 0x88, 0xa3,
	0x7b, 0x7d, 0xc4, 0x85, 0x5d, 0x7e, 0x45, 0x19, 0x1e, 0xb3, 0xbc, 0x2c, 0x02, 0xdf, 0x31, 0xd5,
	0xf0, 0x0f, 0x38, 0x79, 0x85, 0x92, 0x23, 0x0b, 0x7c, 0x07, 0xaa, 0xab, 0x55, 0x88, 0x10, 0xe8,
	0x08, 0xba, 0xe2, 0x8e, 0xa5, 0x2e, 0xa6, 0xce, 0xc4, 0x06, 0xed, 0x13, 0xde, 0x3a, 0xbb, 0x4a,
	0x28, 0x8f, 0xee, 0x5b, 0x00, 0xe5, 0x76, 0x2a, 0xa8, 0x40, 0x02, 0xd0, 0x9d, 0x9d, 0x1d, 0x85,
	0xc1, 0xd8, 0xde, 0x21, 0x16, 0x18, 0xb3, 0x28, 0x38, 0xf7, 0xe6, 0x13, 0xbb, 0xe5, 0xbe, 0x02,
	0x3d, 0x4e, 0x29, 0xe7, 0x52, 0x11, 0x7c, 0xbf, 0xf0, 0xbe, 0xcc, 0xed, 0x9d, 0xea, 0xfc, 0xd1,
	0x3b, 0x97, 0x82, 0x29, 0xe8, 0x2b, 0x39, 0x90, 0x6c, 0xf3, 0xa2, 0x79, 0x30, 0x0e, 0x27, 0x8d,
	0xc7, 0xd4, 0x3f, 0x1b, 0xcf, 0xed, 0x96, 0x04, 0xc7, 0x5e, 0x18, 0x4e, 0xa2, 0xaf, 0x76, 0x9b,
	0x98, 0xa0, 0x9f, 0x07, 0xfe, 0x64, 0x6a, 0x6b, 0xc4, 0x00, 0xed, 0x64, 0x7a, 0x64, 0x77, 0x6a,
	0xf5, 0xc9, 0x64, 0x3c, 0xb7, 0x75, 0xd7, 0x87, 0x5e, 0xb3, 0x56, 0xb2, 0x0f, 0xbd, 0x94, 0x8a,
	0x44, 0x94, 0x4b, 0x54, 0x59, 0x68, 0x47, 0x6b, 0x4c, 0x5e, 0x80, 0x99, 0xe6, 0xd9, 0xaa, 0x2a,
	0xb6, 0x55, 0xf1, 0x8e, 0x70, 0x0f, 0xc1, 0x5c, 0x6f, 0x56, 0xde, 0xfe, 0x27, 0xde, 0xd6, 0x69,
	0x92, 0x47, 0x19, 0xa7, 0x1b, 0x9a, 0x96, 0xeb, 0x38, 0x29, 0xe0, 0xfe, 0x6d, 0x41, 0x2f, 0x42,
	0x5e, 0xe4, 0x19, 0x47, 0xf9, 0x09, 0x90, 0xb1, 0x9c, 0x7d, 0x46, 0xce, 0xe9, 0x0a, 0xeb, 0xee,
	0x07, 0x1c, 0x71, 0xc0, 0xe0, 0x65, 0x1c, 0x23, 0xe7, 0xca, 0xa8, 0x17, 0x35, 0x90, 0xbc, 0x04,
	0x58, 0xe6, 0x71, 0x79, 0x8d, 0x99, 0x08, 0xfc, 0x3a, 0x98, 0xf7, 0x18, 0xf2, 0x0e, 0x8c, 0x3a,
	0x09, 0x2a, 0x98, 0xd6, 0xc8, 0xdd, 0x90, 0x91, 0xfa, 0x51, 0x44, 0x4d, 0x0b, 0xf9, 0x00, 0x66,
	0xa3, 0xae, 0x02, 0xfc, 0xb8, 0xfe, 0xbb, 0xa6, 0xd1, 0x1f, 0x0d, 0xf6, 0x6a, 0x74, 0x5a, 0xa9,
	0xc8, 0x25, 0xf4, 0xc7, 0x0c, 0xa9, 0xc0, 0xe6, 0x0d, 0x3e, 0xc2, 0x72, 0x7f, 0xd3, 0xeb, 0x68,
	0x56, 0xe9, 0xee, 0x90, 0x6f, 0xf0, 0x24, 0x4c, 0xb8, 0x98, 0xfe, 0x98, 0x35, 0x13, 0x6c, 0x74,
	0xaf, 0xff, 0x08, 0x8f, 0x75, 0xbf, 0x00, 0x38, 0x46, 0xb1, 0x85, 0xb1, 0x2f, 0xa1, 0x7f, 0x56,
	0x2c, 0xb7, 0xb3, 0x92, 0x4b, 0xe8, 0xfb, 0x98, 0xe2, 0x36, 0xbc, 0x17, 0x5d, 0xf5, 0xdb, 0x3d,
	0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xd6, 0x81, 0x46, 0x87, 0x05, 0x00, 0x00,
}
