// Code generated by protoc-gen-go. DO NOT EDIT.
// source: publish.proto

package publishen_publish_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request_Class int32

const (
	Request_I_WANT Request_Class = 0
	Request_I_HAVE Request_Class = 1
)

var Request_Class_name = map[int32]string{
	0: "I_WANT",
	1: "I_HAVE",
}

var Request_Class_value = map[string]int32{
	"I_WANT": 0,
	"I_HAVE": 1,
}

func (x Request_Class) String() string {
	return proto.EnumName(Request_Class_name, int32(x))
}

func (Request_Class) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{0, 0}
}

type Request_Group int32

const (
	Request_ARTICLE Request_Group = 0
	Request_PRODUCT Request_Group = 1
	Request_GALLERY Request_Group = 2
	Request_VIDEO   Request_Group = 3
	Request_JOB     Request_Group = 4
	Request_PROJECT Request_Group = 5
)

var Request_Group_name = map[int32]string{
	0: "ARTICLE",
	1: "PRODUCT",
	2: "GALLERY",
	3: "VIDEO",
	4: "JOB",
	5: "PROJECT",
}

var Request_Group_value = map[string]int32{
	"ARTICLE": 0,
	"PRODUCT": 1,
	"GALLERY": 2,
	"VIDEO":   3,
	"JOB":     4,
	"PROJECT": 5,
}

func (x Request_Group) String() string {
	return proto.EnumName(Request_Group_name, int32(x))
}

func (Request_Group) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{0, 1}
}

type Publish_PublishStatus int32

const (
	Publish_ACTIVE     Publish_PublishStatus = 0
	Publish_DEACTIVATE Publish_PublishStatus = 1
)

var Publish_PublishStatus_name = map[int32]string{
	0: "ACTIVE",
	1: "DEACTIVATE",
}

var Publish_PublishStatus_value = map[string]int32{
	"ACTIVE":     0,
	"DEACTIVATE": 1,
}

func (x Publish_PublishStatus) String() string {
	return proto.EnumName(Publish_PublishStatus_name, int32(x))
}

func (Publish_PublishStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{1, 0}
}

type Publish_ShareState int32

const (
	Publish_PUBLIC  Publish_ShareState = 0
	Publish_PRIVATE Publish_ShareState = 1
)

var Publish_ShareState_name = map[int32]string{
	0: "PUBLIC",
	1: "PRIVATE",
}

var Publish_ShareState_value = map[string]int32{
	"PUBLIC":  0,
	"PRIVATE": 1,
}

func (x Publish_ShareState) String() string {
	return proto.EnumName(Publish_ShareState_name, int32(x))
}

func (Publish_ShareState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{1, 1}
}

type Publish_Class int32

const (
	Publish_I_WANT Publish_Class = 0
	Publish_I_HAVE Publish_Class = 1
)

var Publish_Class_name = map[int32]string{
	0: "I_WANT",
	1: "I_HAVE",
}

var Publish_Class_value = map[string]int32{
	"I_WANT": 0,
	"I_HAVE": 1,
}

func (x Publish_Class) String() string {
	return proto.EnumName(Publish_Class_name, int32(x))
}

func (Publish_Class) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{1, 2}
}

type Publish_Group int32

const (
	Publish_ARTICLE Publish_Group = 0
	Publish_PRODUCT Publish_Group = 1
	Publish_GALLERY Publish_Group = 2
	Publish_VIDEO   Publish_Group = 3
	Publish_JOB     Publish_Group = 4
	Publish_PROJECT Publish_Group = 5
)

var Publish_Group_name = map[int32]string{
	0: "ARTICLE",
	1: "PRODUCT",
	2: "GALLERY",
	3: "VIDEO",
	4: "JOB",
	5: "PROJECT",
}

var Publish_Group_value = map[string]int32{
	"ARTICLE": 0,
	"PRODUCT": 1,
	"GALLERY": 2,
	"VIDEO":   3,
	"JOB":     4,
	"PROJECT": 5,
}

func (x Publish_Group) String() string {
	return proto.EnumName(Publish_Group_name, int32(x))
}

func (Publish_Group) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{1, 3}
}

type Request struct {
	Page                 int32         `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32         `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Class                Request_Class `protobuf:"varint,3,opt,name=class,proto3,enum=publishen.publish.service.Request_Class" json:"class,omitempty"`
	Group                Request_Group `protobuf:"varint,4,opt,name=group,proto3,enum=publishen.publish.service.Request_Group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Request) GetClass() Request_Class {
	if m != nil {
		return m.Class
	}
	return Request_I_WANT
}

func (m *Request) GetGroup() Request_Group {
	if m != nil {
		return m.Group
	}
	return Request_ARTICLE
}

type Publish struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string                `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Title                string                `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Banner               string                `protobuf:"bytes,5,opt,name=banner,proto3" json:"banner,omitempty"`
	Images               []string              `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	Location             *Location             `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Attributes           []*Attribute          `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty"`
	ShareGroupId         string                `protobuf:"bytes,9,opt,name=share_group_id,json=shareGroupId,proto3" json:"share_group_id,omitempty"`
	UserId               string                `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tags                 []string              `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt            *timestamp.Timestamp  `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp  `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishStatus        Publish_PublishStatus `protobuf:"varint,14,opt,name=publish_status,json=publishStatus,proto3,enum=publishen.publish.service.Publish_PublishStatus" json:"publish_status,omitempty"`
	ShareState           Publish_ShareState    `protobuf:"varint,15,opt,name=share_state,json=shareState,proto3,enum=publishen.publish.service.Publish_ShareState" json:"share_state,omitempty"`
	Class                Publish_Class         `protobuf:"varint,16,opt,name=class,proto3,enum=publishen.publish.service.Publish_Class" json:"class,omitempty"`
	Group                Publish_Group         `protobuf:"varint,17,opt,name=group,proto3,enum=publishen.publish.service.Publish_Group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Publish) Reset()         { *m = Publish{} }
func (m *Publish) String() string { return proto.CompactTextString(m) }
func (*Publish) ProtoMessage()    {}
func (*Publish) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{1}
}

func (m *Publish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Publish.Unmarshal(m, b)
}
func (m *Publish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Publish.Marshal(b, m, deterministic)
}
func (m *Publish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Publish.Merge(m, src)
}
func (m *Publish) XXX_Size() int {
	return xxx_messageInfo_Publish.Size(m)
}
func (m *Publish) XXX_DiscardUnknown() {
	xxx_messageInfo_Publish.DiscardUnknown(m)
}

var xxx_messageInfo_Publish proto.InternalMessageInfo

func (m *Publish) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Publish) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Publish) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Publish) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Publish) GetBanner() string {
	if m != nil {
		return m.Banner
	}
	return ""
}

func (m *Publish) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Publish) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Publish) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Publish) GetShareGroupId() string {
	if m != nil {
		return m.ShareGroupId
	}
	return ""
}

func (m *Publish) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Publish) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Publish) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Publish) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Publish) GetPublishStatus() Publish_PublishStatus {
	if m != nil {
		return m.PublishStatus
	}
	return Publish_ACTIVE
}

func (m *Publish) GetShareState() Publish_ShareState {
	if m != nil {
		return m.ShareState
	}
	return Publish_PUBLIC
}

func (m *Publish) GetClass() Publish_Class {
	if m != nil {
		return m.Class
	}
	return Publish_I_WANT
}

func (m *Publish) GetGroup() Publish_Group {
	if m != nil {
		return m.Group
	}
	return Publish_ARTICLE
}

type Location struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Attribute struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{3}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Attribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Response struct {
	Code                 int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *Response_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() *Response_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response_Data struct {
	Publish              *Publish   `protobuf:"bytes,2,opt,name=publish,proto3" json:"publish,omitempty"`
	Publishes            []*Publish `protobuf:"bytes,3,rep,name=publishes,proto3" json:"publishes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response_Data) Reset()         { *m = Response_Data{} }
func (m *Response_Data) String() string { return proto.CompactTextString(m) }
func (*Response_Data) ProtoMessage()    {}
func (*Response_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{4, 0}
}

func (m *Response_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Data.Unmarshal(m, b)
}
func (m *Response_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Data.Marshal(b, m, deterministic)
}
func (m *Response_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Data.Merge(m, src)
}
func (m *Response_Data) XXX_Size() int {
	return xxx_messageInfo_Response_Data.Size(m)
}
func (m *Response_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Data proto.InternalMessageInfo

func (m *Response_Data) GetPublish() *Publish {
	if m != nil {
		return m.Publish
	}
	return nil
}

func (m *Response_Data) GetPublishes() []*Publish {
	if m != nil {
		return m.Publishes
	}
	return nil
}

func init() {
	proto.RegisterEnum("publishen.publish.service.Request_Class", Request_Class_name, Request_Class_value)
	proto.RegisterEnum("publishen.publish.service.Request_Group", Request_Group_name, Request_Group_value)
	proto.RegisterEnum("publishen.publish.service.Publish_PublishStatus", Publish_PublishStatus_name, Publish_PublishStatus_value)
	proto.RegisterEnum("publishen.publish.service.Publish_ShareState", Publish_ShareState_name, Publish_ShareState_value)
	proto.RegisterEnum("publishen.publish.service.Publish_Class", Publish_Class_name, Publish_Class_value)
	proto.RegisterEnum("publishen.publish.service.Publish_Group", Publish_Group_name, Publish_Group_value)
	proto.RegisterType((*Request)(nil), "publishen.publish.service.Request")
	proto.RegisterType((*Publish)(nil), "publishen.publish.service.Publish")
	proto.RegisterType((*Location)(nil), "publishen.publish.service.Location")
	proto.RegisterType((*Attribute)(nil), "publishen.publish.service.Attribute")
	proto.RegisterType((*Response)(nil), "publishen.publish.service.Response")
	proto.RegisterType((*Response_Data)(nil), "publishen.publish.service.Response.Data")
}

func init() { proto.RegisterFile("publish.proto", fileDescriptor_34180b7635741fb2) }

var fileDescriptor_34180b7635741fb2 = []byte{
	// 807 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xe1, 0xae, 0xe2, 0x44,
	0x14, 0xbe, 0xa5, 0x94, 0xd2, 0xd3, 0x05, 0xeb, 0x68, 0xb4, 0x12, 0x93, 0x25, 0xdd, 0x35, 0x21,
	0x31, 0x76, 0x0d, 0xfb, 0xcb, 0x64, 0xa3, 0x76, 0x81, 0x5c, 0xd9, 0x90, 0x85, 0xcc, 0x85, 0x7b,
	0xe3, 0xfe, 0xc1, 0x81, 0xce, 0x72, 0x1b, 0x0b, 0xad, 0x9d, 0xe9, 0x4d, 0xf4, 0x01, 0x7c, 0x11,
	0xdf, 0xc8, 0x17, 0xf0, 0x51, 0x34, 0x33, 0xd3, 0x81, 0x7b, 0x13, 0x05, 0xfe, 0x5c, 0x7f, 0x71,
	0xce, 0x99, 0xef, 0x3b, 0x33, 0xe7, 0x70, 0xbe, 0x53, 0x68, 0xe5, 0xe5, 0x2a, 0x4d, 0xd8, 0x6d,
	0x98, 0x17, 0x19, 0xcf, 0xd0, 0x67, 0x95, 0x4b, 0x77, 0xa1, 0x3e, 0x60, 0xb4, 0xb8, 0x4b, 0xd6,
	0xb4, 0xf3, 0x74, 0x93, 0x65, 0x9b, 0x94, 0xbe, 0x90, 0xc0, 0x55, 0xf9, 0xfe, 0x05, 0x4f, 0xb6,
	0x94, 0x71, 0xb2, 0xcd, 0x15, 0x37, 0xf8, 0xa3, 0x06, 0x36, 0xa6, 0xbf, 0x94, 0x94, 0x71, 0x84,
	0xa0, 0x9e, 0x93, 0x0d, 0xf5, 0x8d, 0xae, 0xd1, 0xb3, 0xb0, 0xb4, 0x45, 0x8c, 0x25, 0xbf, 0x51,
	0xbf, 0xa6, 0x62, 0xc2, 0x46, 0xdf, 0x82, 0xb5, 0x4e, 0x09, 0x63, 0xbe, 0xd9, 0x35, 0x7a, 0xed,
	0x7e, 0x2f, 0xfc, 0xcf, 0xfb, 0xc3, 0x2a, 0x75, 0x38, 0x10, 0x78, 0xac, 0x68, 0x82, 0xbf, 0x29,
	0xb2, 0x32, 0xf7, 0xeb, 0x67, 0xf3, 0x2f, 0x05, 0x1e, 0x2b, 0x5a, 0xf0, 0x14, 0x2c, 0x99, 0x0f,
	0x01, 0x34, 0xc6, 0xcb, 0x9b, 0xe8, 0xed, 0xdc, 0xbb, 0x50, 0xf6, 0x0f, 0xd1, 0xf5, 0xc8, 0x33,
	0x82, 0x29, 0x58, 0x92, 0x80, 0x5c, 0xb0, 0x23, 0x3c, 0x1f, 0x0f, 0x26, 0x23, 0xef, 0x42, 0x38,
	0x33, 0x3c, 0x1d, 0x2e, 0x06, 0x73, 0xcf, 0x10, 0xce, 0x65, 0x34, 0x99, 0x8c, 0xf0, 0x8f, 0x5e,
	0x0d, 0x39, 0x60, 0x5d, 0x8f, 0x87, 0xa3, 0xa9, 0x67, 0x22, 0x1b, 0xcc, 0x37, 0xd3, 0xd7, 0x5e,
	0xbd, 0x42, 0xbf, 0x19, 0x0d, 0xe6, 0x9e, 0x15, 0xfc, 0x69, 0x83, 0x3d, 0x53, 0x4f, 0x43, 0x6d,
	0xa8, 0x25, 0xb1, 0xec, 0x91, 0x83, 0x6b, 0x49, 0x8c, 0x3c, 0x30, 0x7f, 0xa6, 0xbf, 0xca, 0x06,
	0x39, 0x58, 0x98, 0xe8, 0x63, 0xb0, 0x78, 0xc2, 0x53, 0x2a, 0xfb, 0xe3, 0x60, 0xe5, 0xa0, 0x2e,
	0xb8, 0x31, 0x65, 0xeb, 0x22, 0xc9, 0x79, 0x92, 0xed, 0x64, 0xed, 0x0e, 0xbe, 0x1f, 0x42, 0x9f,
	0x40, 0x63, 0x45, 0x76, 0x3b, 0x5a, 0xf8, 0x96, 0x3c, 0xac, 0x3c, 0x11, 0x4f, 0xb6, 0x64, 0x43,
	0x99, 0xdf, 0xe8, 0x9a, 0x22, 0xae, 0x3c, 0xf4, 0x1d, 0x34, 0xd3, 0x6c, 0x4d, 0x64, 0x3a, 0xbb,
	0x6b, 0xf4, 0xdc, 0xfe, 0xb3, 0x23, 0xad, 0x9c, 0x54, 0x50, 0xbc, 0x27, 0xa1, 0x21, 0x00, 0xe1,
	0xbc, 0x48, 0x56, 0x25, 0xa7, 0xcc, 0x6f, 0x76, 0xcd, 0x9e, 0xdb, 0x7f, 0x7e, 0x24, 0x45, 0xa4,
	0xc1, 0xf8, 0x1e, 0x0f, 0x3d, 0x87, 0x36, 0xbb, 0x25, 0x05, 0x5d, 0xca, 0x7f, 0x67, 0x99, 0xc4,
	0xbe, 0x23, 0x9f, 0xff, 0x44, 0x46, 0xe5, 0x1f, 0x31, 0x8e, 0xd1, 0xa7, 0x60, 0x97, 0x8c, 0x16,
	0xe2, 0x18, 0x54, 0x75, 0xc2, 0x1d, 0xc7, 0x62, 0xc2, 0x38, 0xd9, 0x30, 0xdf, 0x95, 0xb5, 0x49,
	0x1b, 0x7d, 0x03, 0xb0, 0x2e, 0x28, 0xe1, 0x34, 0x5e, 0x12, 0xee, 0x3f, 0x91, 0xb5, 0x75, 0x42,
	0x35, 0xcb, 0xa1, 0x9e, 0xe5, 0x70, 0xae, 0x67, 0x19, 0x3b, 0x15, 0x3a, 0xe2, 0x82, 0x5a, 0xe6,
	0xb1, 0xa6, 0xb6, 0x4e, 0x53, 0x2b, 0x74, 0xc4, 0xd1, 0x0d, 0xb4, 0xab, 0x8a, 0x97, 0x8c, 0x13,
	0x5e, 0x32, 0xbf, 0x2d, 0x07, 0xf4, 0xeb, 0x23, 0x2d, 0xa9, 0xa6, 0x42, 0xff, 0x5e, 0x49, 0x1e,
	0xd6, 0x02, 0x55, 0x2e, 0x7a, 0x0b, 0xae, 0xea, 0x90, 0x48, 0x4b, 0xfd, 0x0f, 0x64, 0xd6, 0xaf,
	0xce, 0xc8, 0x7a, 0x25, 0x58, 0x22, 0x09, 0xc5, 0xc0, 0xf6, 0xf6, 0x41, 0x80, 0xde, 0x49, 0x01,
	0xe9, 0x4c, 0xff, 0x2e, 0xc0, 0x0f, 0xcf, 0xe6, 0x3f, 0x10, 0xe0, 0x97, 0xd0, 0x7a, 0x50, 0xaf,
	0x10, 0x5f, 0x34, 0x98, 0x8f, 0xaf, 0x85, 0xcc, 0xda, 0x00, 0xc3, 0x91, 0xf4, 0xa2, 0xb9, 0x10,
	0xe3, 0x17, 0x00, 0x87, 0x32, 0x04, 0x72, 0xb6, 0x78, 0x3d, 0x19, 0x0f, 0xb4, 0x20, 0x35, 0xec,
	0xff, 0x17, 0xf5, 0x10, 0x9a, 0x5a, 0x13, 0xa8, 0x03, 0xcd, 0x94, 0xf0, 0x84, 0x97, 0xb1, 0x5a,
	0x7f, 0x35, 0xbc, 0xf7, 0xd1, 0xe7, 0xe0, 0xa4, 0xd9, 0x6e, 0xa3, 0x0e, 0x6b, 0xf2, 0xf0, 0x10,
	0x08, 0x5e, 0x82, 0xb3, 0x97, 0x85, 0xde, 0x05, 0xc6, 0x83, 0x5d, 0x70, 0x47, 0xd2, 0x92, 0x56,
	0xfb, 0x41, 0x39, 0xc1, 0xdf, 0x06, 0x34, 0x31, 0x65, 0x79, 0xb6, 0x63, 0x72, 0xc5, 0xae, 0xb3,
	0x78, 0xbf, 0x76, 0x85, 0x8d, 0x7c, 0xb0, 0xb7, 0x94, 0x31, 0xb1, 0x8d, 0x15, 0x51, 0xbb, 0xe8,
	0x15, 0xd4, 0x63, 0xc2, 0x89, 0xdc, 0x2d, 0xee, 0x89, 0xdd, 0xa9, 0x2e, 0x08, 0x87, 0x84, 0x13,
	0x2c, 0x59, 0x9d, 0xdf, 0x0d, 0xa8, 0x0b, 0x17, 0xbd, 0x02, 0xbb, 0xc2, 0xcb, 0x0b, 0xdc, 0x7e,
	0x70, 0x7a, 0x08, 0xb0, 0xa6, 0xa0, 0xef, 0xc1, 0xd1, 0x68, 0xf1, 0x15, 0x30, 0xcf, 0xe4, 0x1f,
	0x48, 0xfd, 0xbf, 0xcc, 0xbd, 0xd8, 0xae, 0x14, 0x0a, 0xbd, 0x83, 0xd6, 0x40, 0xca, 0x58, 0x6f,
	0xda, 0x33, 0x52, 0x76, 0x9e, 0x9d, 0xd1, 0x80, 0xe0, 0x02, 0xfd, 0x04, 0x1f, 0x4d, 0x12, 0xc6,
	0xa7, 0xef, 0x17, 0x8c, 0x16, 0x33, 0xfd, 0x8a, 0xa3, 0x37, 0x54, 0x9f, 0x9e, 0x73, 0x6f, 0xb8,
	0x01, 0xb8, 0xa4, 0xfc, 0x11, 0x9e, 0xfe, 0x0e, 0x5a, 0x0b, 0xb9, 0xa2, 0x1e, 0x27, 0xf7, 0x90,
	0xa6, 0xf4, 0x31, 0x72, 0xaf, 0x1a, 0x72, 0xd9, 0xbe, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0x67,
	0xe7, 0x73, 0x5f, 0xad, 0x08, 0x00, 0x00,
}
